set -o vi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

export NVM_DIR="/Users/joon/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[[ -r $NVM_DIR/bash_completion ]] && . $NVM_DIR/bash_completion
